numenta/numenta-web

- numenta.com/README.md
- numenta.com/package.json
- numenta.com/pages/applications/_Section.jsx
> WEB-307 fix typo

- numenta.com/README.md
- numenta.com/components/Disqus/index.jsx
- numenta.com/package.json
- numenta.com/wrappers/md.jsx
WEB-174 Add Disqus Comment threads to Posts. 
Original JIRA: https://jira.numenta.com/browse/WEB-174
May take a while to show up as Disqus is updating it's URL index via our updated 301 redirects right now.
cc @jsfowles
> WEB-174 Add Disqus Comment threads to Posts. 

- numenta.com/.eslintrc.json
- numenta.com/README.md
- numenta.com/components/Search/index.jsx
- numenta.com/package.json
- numenta.com/pages/anomaly-detection-benchmark/index.jsx
- numenta.com/pages/applications/index.jsx
- numenta.com/pages/business-strategy-and-ip/index.jsx
- numenta.com/pages/careers-and-team/index.jsx
- numenta.com/pages/contact/index.jsx
- numenta.com/pages/index.jsx
- numenta.com/pages/mission-and-history/index.jsx
- numenta.com/pages/open-source-community/index.jsx
- numenta.com/pages/papers-videos-and-more/index.jsx
- numenta.com/pages/partners/index.jsx
- numenta.com/pages/technology-overview/index.jsx
- numenta.com/wrappers/md.jsx
WEB-174 Disqus comments load after component mount for client only.
Also: pkg bump, stamp version on search index call, lint changes, and dox.
orig: https://jira.numenta.com/browse/WEB-174
cc @jsfowles
> WEB-174 Disqus comments load after component mount for client only.

- numenta.com/wrappers/md.jsx
Issue #64 fix disqus leak onto non-Post markdown pages (404, etc).
https://github.com/numenta/numenta-web/issues/64
> Issue #64 fix disqus leak onto non-Post markdown pages (404, etc).

- numenta.com/package.json
- numenta.com/pages/htm-studio/faq/open-source.md
- numenta.com/pages/htm-studio/faq/whats-next.md
WEB-324 New HTM Studio page FAQ section on Open Source repo.
https://jira.numenta.com/browse/WEB-324
> WEB-324 New HTM Studio page FAQ section on Open Source repo.

- numenta.com/components/Markdown/index.jsx
- numenta.com/package.json
WEB-319 Trying to fix some md links (Careers Apply Now button, etc).
https://jira.numenta.com/browse/WEB-319
> WEB-319 Trying to fix some md links (Careers Apply Now button, etc).

- numenta.com/pages/press/2016/10/19/field-report-oreilly-artificial-intelligence-conference.md
WEB-327 new press link
https://jira.numenta.com/browse/WEB-327
> WEB-327 new press link

- numenta.com/pages/papers/continuous-online-sequence-learning-with-an-unsupervised-neural-network-model.md
- numenta.com/pages/papers/htm-spatial-pooler-neocortical-algorithm-for-online-sparse-distributed-coding.md
- numenta.com/pages/papers/why-neurons-have-thousands-of-synapses-theory-of-sequence-memory-in-neocortex.md
https://jira.numenta.com/browse/WEB-352
> WEB-352 Patches to Papers

- packages/numenta.org/pages/_Section.jsx
WEB-368 Homepage welcome text.
https://jira.numenta.com/browse/WEB-368
> WEB-368 Homepage welcome text.

- packages/numenta.org/pages/papers/continuous-online-sequence-learning-with-an-unsupervised-neural-network-model.md
- packages/numenta.org/pages/papers/why-neurons-have-thousands-of-synapses-theory-of-sequence-memory-in-neocortex.md
- packages/numenta.org/wrappers/md.jsx
https://jira.numenta.com/browse/WEB-389
> WEB-389 Christy changes from today email/worddoc

- packages/numenta.com/package.json
- packages/numenta.com/pages/press/2016/11/18/upside-briefing-numenta.md
https://jira.numenta.com/browse/WEB-373
> WEB-373 new press TDWI

- packages/numenta.com/pages/press/2016/11/30/how-artificial-intelligence-and-robots-will-radically-transform-the-economy.md
https://jira.numenta.com/browse/WEB-397
> WEB-397 new press link

- packages/components/Quote/__tests__/index.unit.test.jsx
- packages/components/Quote/index.css
- packages/components/Quote/index.jsx
- packages/numenta.org/pages/_Section.jsx
- packages/numenta.org/pages/index.jsx
- packages/numenta.org/pages/research-and-publications/_Section.jsx
https://jira.numenta.com/browse/WEB-383
> WEB-383 add quote component, style, etc.

- packages/components/Tag/index.css
- packages/numenta.org/pages/_Section.jsx
This will probably need to be cleaned up on .com for next release a little, but looks better
overall and should be kept for .org at least.
https://jira.numenta.com/browse/WEB-396
> WEB-396 make tag bit bigger and more pronounced per @twirfs. 

- packages/numenta.org/pages/events/index.jsx
https://jira.numenta.com/browse/WEB-394
> WEB-394 No events? Link to numenta.com/events.

- packages/numenta.org/pages/papers/continuous-online-sequence-learning-with-an-unsupervised-neural-network-model.md
https://jira.numenta.com/browse/WEB-401
> WEB-401 changes to Seq paper

- packages/numenta.org/wrappers/md.jsx
https://jira.numenta.com/browse/WEB-390
https://jira.numenta.com/browse/WEB-400
> WEB-390 WEB-400 adjust papers

- packages/numenta.org/config.toml
- packages/numenta.org/pages/_MainSections.jsx
- packages/numenta.org/pages/index.jsx
https://jira.numenta.com/browse/WEB-392
> WEB-392 tweak / capitalization

- packages/numenta.org/config.toml
- packages/numenta.org/package.json
- packages/numenta.org/pages/_Section.jsx
https://jira.numenta.com/browse/WEB-408
> WEB-408 glance changes

- packages/components/Video/index.css
- packages/components/Video/index.jsx
WEB-414 add close icon+button to top-right of video player box.
https://jira.numenta.com/browse/WEB-414
> WEB-414 add close icon+button to top-right of video player box.

- packages/components/Search/index.jsx
- packages/numenta.org/components/Header/index.jsx
WEB-382 better search button color for new .org site
https://jira.numenta.com/browse/WEB-382
> WEB-382 better search button color for new .org site

- package.json
- packages/components/package.json
- packages/components/src/Disqus/index.jsx
- packages/components/src/Markdown/index.jsx
- packages/components/src/Section/index.jsx
- packages/numenta.com/gatsby-browser.js
- packages/numenta.com/package.json
- packages/numenta.com/pages/_MainSections.jsx
- packages/numenta.com/wrappers/md.jsx
- packages/numenta.org/gatsby-browser.js
- packages/numenta.org/package.json
- packages/numenta.org/pages/_MainSections.jsx
- packages/utils/package.json
- packages/utils/src/client.js
Think I've got the last test fixed for Bamboo
cc @rhyolight
> Think I've got the last test fixed for Bamboo

- __tests__/__setup.js
- package.json
Add JUnit test result output, for Bamboo build interface.
cc @rhyolight
> Add JUnit test result output, for Bamboo build interface.

- README.md
- package.json
WEB-430 note node/npm version, and note for older versions per @lscheinkman
> WEB-430 note node/npm version, and note for older versions per Luiz.

- TODO.md
- packages/numenta.com/pages/_template.jsx
- packages/numenta.org/.gitignore
- packages/numenta.org/pages/_template.jsx
Fix inline css on dev
should fix @rhyolight problems from PR #131 
Only try to load production css during production builld/mode.
cc @lscheinkman
> Fix inline css on dev

- packages/numenta.com/__tests__/pages/__snapshots__/anomaly-detection-benchmark.unit.test.jsx.snap
- packages/numenta.com/__tests__/pages/__snapshots__/applications.unit.test.jsx.snap
- packages/numenta.com/__tests__/pages/__snapshots__/business-strategy-and-ip.unit.test.jsx.snap
- packages/numenta.com/__tests__/pages/__snapshots__/careers-and-team.unit.test.jsx.snap
- packages/numenta.com/__tests__/pages/__snapshots__/contact.unit.test.jsx.snap
- packages/numenta.com/__tests__/pages/__snapshots__/index.unit.test.jsx.snap
- packages/numenta.com/__tests__/pages/__snapshots__/machine-intelligence-technology.unit.test.jsx.snap
- packages/numenta.com/__tests__/pages/__snapshots__/mission-and-history.unit.test.jsx.snap
- packages/numenta.com/__tests__/pages/__snapshots__/neuroscience-research.unit.test.jsx.snap
- packages/numenta.com/__tests__/pages/__snapshots__/open-source-community.unit.test.jsx.snap
- packages/numenta.com/__tests__/pages/__snapshots__/papers-videos-and-more.unit.test.jsx.snap
- packages/numenta.com/__tests__/pages/__snapshots__/partners.unit.test.jsx.snap
- packages/numenta.com/config.toml
- packages/numenta.com/pages/careers-and-team/_Section.jsx
- packages/numenta.com/pages/careers-and-team/careers/visiting-scholar-program.md
- packages/numenta.com/pages/neuroscience-research/_Section.jsx
@brev Please review.
I've put the tests in a separated commit so it is easier to review.
You can check the results on my forks's gh-pages: https://lscheinkman.github.io/numenta-web/
CC: @rhyolight
> WEB-433: Add visiting scholar program

- packages/numenta.com/__tests__/pages/__snapshots__/anomaly-detection-benchmark.unit.test.jsx.snap
- packages/numenta.com/__tests__/pages/__snapshots__/applications.unit.test.jsx.snap
- packages/numenta.com/__tests__/pages/__snapshots__/business-strategy-and-ip.unit.test.jsx.snap
- packages/numenta.com/__tests__/pages/__snapshots__/careers-and-team.unit.test.jsx.snap
- packages/numenta.com/__tests__/pages/__snapshots__/contact.unit.test.jsx.snap
- packages/numenta.com/__tests__/pages/__snapshots__/index.unit.test.jsx.snap
- packages/numenta.com/__tests__/pages/__snapshots__/machine-intelligence-technology.unit.test.jsx.snap
- packages/numenta.com/__tests__/pages/__snapshots__/mission-and-history.unit.test.jsx.snap
- packages/numenta.com/__tests__/pages/__snapshots__/neuroscience-research.unit.test.jsx.snap
- packages/numenta.com/__tests__/pages/__snapshots__/open-source-community.unit.test.jsx.snap
- packages/numenta.com/__tests__/pages/__snapshots__/papers-videos-and-more.unit.test.jsx.snap
- packages/numenta.com/__tests__/pages/__snapshots__/partners.unit.test.jsx.snap
- packages/numenta.com/pages/neuroscience-research/_Section.jsx
Update 'Neuroscience Research' page per @subutai feedback
> WEB-433: Update Neuroscience Research Page

- packages/numenta.com/pages/_Section.jsx
Content change requested by @cmaver 
CC: @rhyolight
> Add link to numenta.org

- packages/numenta.com/pages/careers-and-team/careers/marketing-associate.md
Added writing samples to last bullet
> Writing samples in last bullet

- packages/numenta.org/__tests__/pages/__snapshots__/htm-school.unit.test.jsx.snap
- packages/numenta.org/config.toml
- packages/numenta.org/pages/htm-school/index.jsx
> [WEB-460] linked to papers from htm school

- packages/numenta.org/__tests__/pages/__snapshots__/htm-school.unit.test.jsx.snap
- packages/numenta.org/__tests__/pages/__snapshots__/implementations.unit.test.jsx.snap
- packages/numenta.org/pages/htm-school/index.jsx
- packages/numenta.org/pages/implementations/index.jsx
Add snapshots for #165 
@cmaver
> Add snapshots pr165

- packages/numenta.org/wrappers/md.jsx
> WEB-471: All Blog Posts

- packages/numenta.org/s3_redirect.xml
> added .org redirects

- package.json
but this time update snapshots on the fly.
> Fix broken CI builds by running tests

- packages/numenta.com/pages/events/2015/08/18/dataversity-smart-data-conference-san-jose-2015.md
- packages/numenta.com/pages/newsletter/2015/07/02/announcing-open-source-htm-app-grok-for-stocks.md
- packages/numenta.com/pages/newsletter/2016/02/18/htm-for-stocks-available-in-the-app-store.md
- packages/numenta.com/pages/press/2015/08/19/numenta-announces-licensing-of-grok-for-it-to-avik-partners.md
- packages/numenta.org/pages/blog/2015/08/03/htm-engine-tutorial.md
@cmaver Just in case you want to fix the links with the extra '/'
> Fix htm-for-stocks links

- packages/numenta.com/config.toml
- packages/numenta.com/pages/business-strategy-and-ip/_Section.jsx
- packages/numenta.com/pages/mission-and-history/_Section.jsx
- packages/numenta.com/pages/open-source-community/_Section.jsx
- packages/numenta.com/pages/partners/_Section.jsx
Reverts numenta/numenta-web#272
> Revert "Revert licence update"

- packages/numenta.com/__tests__/pages/__snapshots__/papers-videos-and-more.unit.test.jsx.snap
- packages/numenta.com/pages/papers-videos-and-more/_Section.jsx
Fix misaligned column under PapersVideosMore main section.
@lscheinkman plz review thx.
> Fix misaligned column under PapersVideosMore main section.

- packages/numenta.com/__tests__/pages/__snapshots__/sitemap.unit.test.jsx.snap
- packages/numenta.com/config.toml
- packages/numenta.com/pages/sitemap/index.jsx
Add Nutshell page that was missing from Sitemap.
@lscheinkman plz review thx.
> Add Nutshell page that was missing from Sitemap.

- packages/numenta.com/__tests__/pages/__snapshots__/anomaly-detection-benchmark.unit.test.jsx.snap
- packages/numenta.com/__tests__/pages/__snapshots__/applications.unit.test.jsx.snap
- packages/numenta.com/__tests__/pages/__snapshots__/business-strategy-and-ip.unit.test.jsx.snap
- packages/numenta.com/__tests__/pages/__snapshots__/careers-and-team.unit.test.jsx.snap
- packages/numenta.com/__tests__/pages/__snapshots__/contact.unit.test.jsx.snap
- packages/numenta.com/__tests__/pages/__snapshots__/index.unit.test.jsx.snap
- packages/numenta.com/__tests__/pages/__snapshots__/machine-intelligence-technology.unit.test.jsx.snap
- packages/numenta.com/__tests__/pages/__snapshots__/mission-and-history.unit.test.jsx.snap
- packages/numenta.com/__tests__/pages/__snapshots__/neuroscience-research.unit.test.jsx.snap
- packages/numenta.com/__tests__/pages/__snapshots__/open-source-community.unit.test.jsx.snap
- packages/numenta.com/__tests__/pages/__snapshots__/partners.unit.test.jsx.snap
Update lagging unit test snapshots to current (my four PRs have been merged already).
@lscheinkman plz review thx.
> Update unit test snapshots to current.

- packages/numenta.com/pages/papers/why-does-the-neocortex-have-layers-and-columns.md
@cmaver This should fix the broken link in latest build
> Fix broken link
